spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile}

server:
  port: 9070
  compression:
    enabled: true
  
logging:
  file: D:/Test/log/portal/apollo-portal.log

management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


